name = "roadmail"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "EMAIL_LOGS"
id = "roadmail-logs"

[[queues.producers]]
queue = "roadmail-queue"
binding = "EMAIL_QUEUE"

[[queues.consumers]]
queue = "roadmail-queue"
max_batch_size = 10
max_batch_timeout = 30

[vars]
DEFAULT_FROM = "noreply@blackroad.io"
